Part1
altimetrik-onboarding-uy/acanavesi-onboarding pull request #13
Opened 2016-11-17 19:49 UTC by acanavesialtimetrik

Part 1 and 2 finished

2016-11-18 02:01 UTC, rjulianialtimetrik commented on src/classes/ExpensesController.cls
> +        ' LIMIT 100');
Limiting this query to only 100 results might not be ideal. please review Salesforce's Governor Limits and use a number  that makes more sense

2016-11-18 02:55 UTC, rjulianialtimetrik requested changes

2016-11-18 02:55 UTC, rjulianialtimetrik commented on src/triggers/DeletionRules.trigger
> +trigger DeletionRules on Expense__c (after update, after delete) {
It's recommended to use the object's name as part of a trigger's name. For example, this trigger could be called ExpenseDeletionRules

2016-11-21 12:26 UTC, rjulianialtimetrik approved these changes
Looks pretty good! I'm just going to ask you to please add pagination to your list

2016-11-21 12:35 UTC, merged

2016-11-21 12:37 UTC, acanavesialtimetrik commented
Yes, pagination is still a pending task, I was finishing other issues related to part 3 and then I get back to here.